name: Build APK

on:
  push:
    branches:
      - main  # замените на вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev python3-pil python3-setuptools python3-venv python3-wheel python3-xlib
        pip install kivy cython

    - name: Install Android SDK components
      run: |
        mkdir -p ~/.android-sdk
        cd ~/.android-sdk
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        yes | tools/bin/sdkmanager "platforms;android-29" "build-tools;29.0.3" "extras;android;m2repository" "extras;google;m2repository" "extras;google;google_play_services"
        export ANDROID_HOME=~/.android-sdk
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        export PATH=$PATH:$ANDROID_HOME/tools
        export PATH=$PATH:$ANDROID_HOME/tools/bin

    - name: Build APK
      run: |
        python -m pip install --upgrade buildozer
        buildozer init
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: ./bin/*.apk
