- name: Install build dependencies
  run: |
    sudo apt update
    sudo apt install -y \
      git \
      zip \
      unzip \
      python3-pip \
      python3-distutils \  # Добавлено python3-distutils
      build-essential \
      autoconf \
      libtool \
      pkg-config \
      zlib1g-dev \
      libncurses5-dev \
      libncursesw5-dev \
      libtinfo5 \
      libffi-dev \
      libssl-dev \
      libsqlite3-dev \
      libbz2-dev \
      libreadline-dev \
      tk-dev
    pip install --upgrade pip
