name: Build APK

on:
  push:
    branches:
      - main  # замените на вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev python3-pil python3-setuptools python3-venv python3-wheel python3-xlib
        pip install kivy cython

    - name: Accept Android SDK licenses and install required components
      run: |
        yes | sdkmanager --licenses
        sdkmanager "build-tools;35.0.0-rc3" "platforms;android-31" "platform-tools" "tools"
        sdkmanager --install "platforms;android-31" "build-tools;35.0.0-rc3"
        sdkmanager "extras;android;m2repository" "extras;google;m2repository" "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
        sdkmanager --update

    - name: Build APK
      run: |
        python -m pip install --upgrade buildozer
        buildozer init
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: ./bin/*.apk
