name: Build APK

on:
  push:
    branches:
      - main  # замените на вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev python3-pil python3-setuptools python3-venv python3-wheel python3-xlib
        pip install kivy cython

    - name: Install Android build tools
      run: |
        sudo apt-get install -y openjdk-8-jdk
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        sudo apt-get install -y android-sdk
        sudo apt-get install -y android-sdk-build-tools
        sudo apt-get install -y android-sdk-platform-tools
        sudo apt-get install -y android-sdk-platforms
        sudo apt-get install -y android-sdk-tools

    - name: Install aidl
      run: |
        sudo apt-get install -y aidl

    - name: Build APK
      run: |
        python -m pip install --upgrade buildozer
        buildozer init
        cp ./*.py ./*.kv ./*.png ./  # Это скопирует все файлы Python, KV и PNG из корневой папки в рабочую директорию
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: ./bin/*.apk
