name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip build-essential git python3 python3-dev python3-pil python3-setuptools python3-venv python3-wheel python3-xlib
        pip install kivy cython

    # Устанавливаем Android SDK Build-Tools и принимаем лицензию
    - name: Install Android SDK Build-Tools
      run: |
        echo y | sdkmanager --licenses
        sudo apt-get install -y android-sdk-build-tools

    # Проверяем наличие Aidl
    - name: Check for Aidl
      run: |
        if ! command -v aidl &> /dev/null
        then
            echo "Aidl not found, please install it."
            exit 1
        fi

    - name: Build APK
      run: |
        python -m pip install --upgrade buildozer
        buildozer init
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: ./bin/*.apk
