name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

    - name: Install distutils
      run: sudo apt-get install python3-distutils

    - name: Install buildozer
      run: pip install buildozer

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Android app
      run: |
        buildozer init
        buildozer -v android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-build
        path: ./bin/*.apk
